### ISSUE TITLE
Add Scroll to Top Button

### ISSUE THREAD

**Issue by SattyamSamania** [RahulSharma4329/Bandhu-Card-Landing-Page#3] opened 2022-12-08 16:18 UTC
I would like to add Scroll to Top Button to add more interactivity for the users and we do not have to scroll back again and again. I can create  Scroll Button using HTML, CSS and JS. If you think that would be valuable feature kindly assign this issue to me. Thank You!

**Comment by RahulSharma4329** [comment] 2022-12-08 17:29
I have assigned the Issue to you. Please create a new branch and contribute.

**Comment by SattyamSamania** [comment] 2022-12-09 03:51
@RahulSharma4329 Why it's showing react-scripts' is not recognized as an internal or external command, after i run npm start?

**Comment by RahulSharma4329** [comment] 2022-12-09 07:33
Do a npm install

**Comment by SattyamSamania** [comment] 2022-12-09 09:27
> Do a npm install

@RahulSharma4329 Its opening on local host but nothing is showing. I can see the title only.

**Comment by RahulSharma4329** [comment] 2022-12-09 10:47
The home page url is bugyy 

Try to go to 

localhost:3000/

it will open 

ill am fixing this issue asap

**Comment by RahulSharma4329** [comment] 2022-12-09 10:58
i have fixed the issue do a git pull and everything should work fine

**Comment by himanshu1221** [comment] 2022-12-11 12:48
If the issue is not resolved can you please assign this to me ?

**Comment by RahulSharma4329** [comment] 2022-12-11 13:00
Let's give @SattyamSamania a little more time to solve the issue. If it would not be resolved even after a couple of days I'll ask him and assign it to you @himanshu1221

**Comment by SattyamSamania** [comment] 2022-12-11 13:57
> Let's give @SattyamSamania a little more time to solve the issue. If it would not be resolved even after a couple of days I'll ask him and assign it to you @himanshu1221 

I think I made the PR. It has to be reviewed by you first.

**Closed as completed** 2022-12-11 17:46 UTC
